# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

name: TRGoals, MonoTV ve M3U Güncelleme Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:  # Manuel tetikleme için
  schedule:
    - cron: '*/10 * * * *'  # Her 10 dakikada bir çalışır
    - cron: '0 * * * *'     # Her saat başı çalışır (M3U güncellemesi için)

jobs:
  DomainKontrol:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4.2.2

      - name: Python 3.11.8 Yükle
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.11.8

      - name: Python Sürümünü Göster
        run: python -c "import sys; print(sys.version)"

      - name: Gereksinimleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel Kekik httpx parsel

      - name: TRGoals.py Çalıştır
        run: |
          python TRGoals.py

      - name: MonoTV.py Çalıştır
        run: |
          python MonoTV.py

      - name: Değişiklik Kontrolü
        id: degisiklik_kontrol
        run: |
          git diff --quiet . || echo "degisiklik=true" >> $GITHUB_OUTPUT

      - name: Değişiklikleri Commit Et
        if: steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "♻️ Yayın linkleri güncellendi (TRGoals & MonoTV)" -m "🕒 Otomatik işlem - $GITHUB_SHA"
          git push

  update-m3u:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Depo Kontrolü
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Gerekli Paketleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: M3U Listesini İndir ve Güncelle
        run: |
          # M3U listesini indir ve yeni.m3u dosyasına kaydet
          curl -s "https://sakultah.org/playlist1.m3u" > yeni.m3u
          
          # Python script ile subatv.m3u dosyasını güncelle
          cat > update_m3u.py << 'EOF'
          import re
          import os
          
          def parse_m3u(file_path):
              """M3U dosyasını parse eder ve kanal ID-URL eşleşmelerini döndürür"""
              channels = {}
              current_id = None
              
              with open(file_path, 'r', encoding='utf-8') as f:
                  for line in f:
                      line = line.strip()
                      if line.startswith('#EXTINF'):
                          # Kanal ID'sini çıkar
                          match = re.search('tvg-id="([^"]+)"', line)
                          if match:
                              current_id = match.group(1)
                          else:
                              current_id = None
                      elif line and not line.startswith('#') and current_id:
                          # URL satırı
                          channels[current_id] = line
                          current_id = None
              
              return channels
          
          def update_subatv_m3u():
              """subatv.m3u dosyasındaki kanalların URL'lerini yeni.m3u'dan alınanlarla günceller"""
              # Yeni M3U dosyasından kanal-URL eşleşmelerini al
              new_channels = parse_m3u('yeni.m3u')
              
              if not os.path.exists('subatv.m3u'):
                  print("subatv.m3u dosyası bulunamadı, oluşturuluyor...")
                  with open('subatv.m3u', 'w', encoding='utf-8') as f:
                      f.write("#EXTM3U\n")
              
              # subatv.m3u dosyasını oku
              with open('subatv.m3u', 'r', encoding='utf-8') as f:
                  lines = f.readlines()
              
              updated_lines = []
              i = 0
              while i < len(lines):
                  line = lines[i].strip()
                  updated_lines.append(lines[i])
                  
                  if line.startswith('#EXTINF'):
                      # Kanal ID'sini bul
                      match = re.search('tvg-id="([^"]+)"', line)
                      channel_id = None
                      if match:
                          channel_id = match.group(1)
                      
                      # Bir sonraki satır URL olmalı
                      if i + 1 < len(lines) and channel_id and channel_id in new_channels:
                          # URL'yi güncelle
                          i += 1  # URL satırına geç
                          updated_lines.append(new_channels[channel_id] + '\n')
                      elif i + 1 < len(lines):
                          # Kanal bulunamadı veya eşleşme yok, orijinal URL'yi koru
                          i += 1
                          updated_lines.append(lines[i])
                  i += 1
              
              # Güncellenmiş içeriği yaz
              with open('subatv.m3u', 'w', encoding='utf-8') as f:
                  f.writelines(updated_lines)
              
              print("subatv.m3u dosyası başarıyla güncellendi!")
          
          if __name__ == "__main__":
              update_subatv_m3u()
          EOF
          
          # Python scriptini çalıştır
          python update_m3u.py

      - name: Değişiklikleri Commit ve Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add yeni.m3u subatv.m3u
          git commit -m "M3U listeleri otomatik olarak güncellendi" || echo "Değişiklik yok"
          git push https://${{ secrets.PAT }}@github.com/kerimmkirac/CanliTvListe.git
