name: Vavoo M3U Güncelle

on:
  schedule:
    - cron: '0 */10 * * *'  
  workflow_dispatch:       

jobs:
  update-vavoo:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Gerekli paketleri yükle
        run: pip install requests

      - name: Vavoo M3U dosyasını oluştur
        run: python vavoo.py

      - name: Değişiklik kontrolü
        id: git-check
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit ve push (eğer değişiklik varsa)
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git add vavoo.m3u
          git commit -m "🔁 vavoo.m3u güncellendi - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
